rails5/config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  if Rails.env.test?
    match '/:controller/:action'
  end
end

rails5/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails5/app/models/thing.rb
class Thing < ApplicationRecord
  def self.self_and_descendants_for(id)
    where(<<-SQL, id: id)
      #{quoted_table_name}.#{quoted_primary_key} IN (
        WITH RECURSIVE descendant_tree(#{quoted_primary_key}, path) AS (
            SELECT #{quoted_primary_key}, ARRAY[#{quoted_primary_key}]
            FROM #{quoted_table_name}
            WHERE #{quoted_primary_key} = :id
          UNION ALL
            SELECT #{quoted_table_name}.#{quoted_primary_key}, descendant_tree.path || #{quoted_table_name}.#{quoted_primary_key}
            FROM descendant_tree
            JOIN #{quoted_table_name} ON #{quoted_table_name}.parent_id = descendant_tree.#{quoted_primary_key}
            WHERE NOT #{quoted_table_name}.#{quoted_primary_key} = ANY(descendant_tree.path)
        )
        SELECT #{quoted_primary_key}
        FROM descendant_tree
        ORDER BY path
      )
     SQL
  end
end

rails5/app/models/user.rb
class User < ApplicationRecord
  def self.evaluate_user_input
    eval(params)
  end

  def evaluate_user_input
    self.class.evaluate_user_input
  end

  def test_stuff
    if Rails.env.test?
      User.where(params)
    end
  end

  has_many :things,
    -> { where(Thing.canadian.where_values_hash) }

  def self.all_that_jazz(user)
    User.where(User.access_condition(user))
  end

  belongs_to :matched_user, class_name: 'User', optional: true
end

rails5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails5/app/controllers/concerns/concerning.rb
module Concerning
  extend ActiveSupport::Concern

  included do
    include Concerning
  end
end

rails5/app/controllers/concerns/forgery_protection.rb
module ForgeryProtection
  extend ActiveSupport::Concern

  included do
    protect_from_forgery with: :exception
  end
end

rails5/app/controllers/mixed_controller.rb
class BaseController < ActionController::Base
  # No protect_from_forgery call, but one mixed in
  include ForgeryProtection
  include Concerning

  Statistics::AdminWithdrawal::BANK_LIST = [:deutsche, :boa, :jpm_chase, :cyprus]

  def another_early_return
    bank_name = params[:filename].first
    unless Statistics::AdminWithdrawal::BANK_LIST.include?(bank_name)
      flash[:alert] = 'Invalid filename'
      redirect_to :back
      return
    end

    Statistics::AdminWithdrawal.send("export_#{bank_name}_#inc!")
  end

  def yet_another_early_return
    scope_name = params[:scope].presence
    fail ActiveRecord::RecordNotFound unless ['safe', 'also_safe'].include?(scope_name)
    Model.public_send(scope_name)
  end

  def redirect_to_strong_params
    redirect_to params.permit(:domain) # should warn
    redirect_to params.permit(:page, :sort) # should not warn
  end
end

rails5/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end

    def ruby_230
      x&.send(params[:x])
      a&.b ||= blah
      params.permit!
      User.new&.attributes = params
    end

    def symbol
      params[:x].to_sym
    end

    def slice_then_permit
      User.new(params.slice(:id).permit!)
      User.find_by(params.slice(:id))
      redirect_to params.slice(:back_to)
    end

    def nested_sql_interp 
      User.connection.execute("SELECT * FROM foo WHERE #{true ? "bar = #{ActiveRecord::Base.connection.quote(true)}" : "bar = 0"}")
    end

    def arel_sql
      Arel.sql("select #{params[:s]}")
    end
end

rails5/app/controllers/widget_controller.rb
class WidgetController < ApplicationController
  def show
  end

  def dynamic_constant
    identifier_class = params[:IdentifierClass]
    namespace = identifier_class.constantize::IDENTIFIER_NAMESPACE # should warn
  end

  def render_thing
    render params[:x].thing?
  end

  def render_inline
    render :inline => "<%= xss.html_safe %>", :content_type => "text/html", :locals => { :xss => params[:xss] }
  end

  def sql_with_case
    group_by_col =
      case params[:group_by]
      when 'brand'            then 'brand'
      when 'year'             then 'YEAR(date_utc)'
      when 'month'            then "CONCAT(YEAR(date_utc), '-', LPAD(MONTH(date_utc), 2, '0'))"
      when 'week'             then "CONCAT(YEAR(date_utc), '-', LPAD(WEEK(date_utc, 1), 2, '0'))"
      when 'day'              then "DATE(date_utc)"
      else raise ArgumentError, 'Invalid group by value'
      end

    query = "SELECT id, #{group_by_col} AS group_by_col, COUNT(*) FROM records"

    # No warnings
    rows = User.connection.select_rows(query)
  end

  def sql_with_another_case
    subset_clause = case script_subset
                    when :greasyfork
                      "AND `sensitive` = false"
                    when :sleazyfork
                      "AND `sensitive` = true"
                    else
                      ""
                    end
    sql =<<-EOF
  SELECT
    text, SUM(daily_installs) install_count, COUNT(s.id) script_count
  FROM script_applies_tos
  JOIN scripts s ON script_id = s.id
  WHERE
    domain
    AND script_type_id = 1
    AND script_delete_type_id IS NULL
    AND !tld_extra
    #{subset_clause}
  GROUP BY text
  ORDER BY text
    EOF

    # No warnings
    by_sites = User.connection.select_rows(sql)
  end

  def render_with_case
    # No warnings
    case params[:switch_case_on_this]
    when "one"
      render partial: params[:switch_case_on_this], locals: { x: 1 }
    when "two"
      render partial: params[:switch_case_on_this], locals: { x: 2 }
    end
  end

  def no_html
    @x = params[:x].html_safe
  end

  def guard_with_return
    goto = params[:goto]
    event = params[:event]
    return redirect_to user_path unless %w[comment subscribe].include?(goto)

    redirect_to send("#{goto}_event_path", event) # should not warn
  end

  def render_cookies
    render inline: request.cookies["value"]
  end

  def dangerous_permits
    params.permit(:admin)
    params.permit(:role_id)
  end

  def redirect_to_path
    session = User.find_by_token params[:session]

    if session
      # proceed with extracting user context from session and more and redirect to the last path the user was shown to
      login(session.user)
      redirect_to session.user.current_path
    else
      redirect_to expired_or_invalid_session_path
    end
  end

  def render_safely
    slug = params[:slug].to_s
    render slug if template_exists?(slug, 'pages')
  end
end

IDENTIFIER_NAMESPACE = 'apis'

rails5/app/helpers/application_helper.rb
module ApplicationHelper
end

rails5/app/helpers/users_helper.rb
module UsersHelper
  def bad_helper
    eval(params[:x])
  end
end

rails5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails5/app/views/layouts/users.html.erb
<% if @user %>
  <%= @user.name.html_safe %>
<% end %>

rails5/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails5/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

rails5/app/views/users/find_and_preserve.html.haml
= find_and_preserve do
  %pre
    :escaped
      <p class="input-container input-container-5">
        <label for="f1">Name</label>
        <input class="input" id="f1" placeholder=".input-container-5" type="text">
      </p>
      <p class="input-container input-container-10">
        <label for="f2">Address</label>
        <input class="input" id="f2" placeholder=".input-container-10" type="text">
      </p>

rails5/app/views/users/if_thing.html.haml
:javascript
  #{j(params[:a])} // Should not warn
  #{j(params[:b]) unless params[:c]} // Should not warn

rails5/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'slice', params.slice(:url) %>

rails5/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

rails5/app/views/users/safe_call_params.html.haml
:javascript
  factory.printing.copies = #{params[:copies]&.to_i || 1};

rails5/app/views/users/sanitizing.html.erb
<%= raw sanitize(params[:x]) %>

<%= strip_tags(params[:x]).html_safe %>

rails5/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<%= link_to("good", params.merge(:page => 2)) %>
<%= link_to("xss", url_for(params[:bad])) %>

rails5/app/views/widget/content_tag.html.erb
<%= content_tag(:div, "hi", title: params[:stuff].html_safe) %>

<%= content_tag(:div, "hi", title: sanitize(params[:stuff])) %>

rails5/app/views/widget/graphql.html.erb
<%graphql
  fragment Thing on Thing {
    thingHTML

    ...Views::Things::ThingHeader::Thing
  }
%>

rails5/app/views/widget/no_html.haml
%h1= @x

rails5/app/views/widget/show.html.erb
<%= params[:x].html_safe unless this_is_a_bad_idea? %>

<%= link_to("Thing", "#{ENV['SOME_URL']}#{params[:x]}") %>
<%= link_to("Email!", "mailto:#{params[:x]}") %>